name: 'Planning Algorithm Week'
description: 'Algorithm week-based task planning'
title: '[Week1] EunseoPark'
labels: ['week', 'problems']
body:
  - type: textarea
    id: tasks
    attributes:
      label: "✅ To-do"
      description: "해당 기능을 구현하기 위한 세부 작업 목록을 작성해주세요."
      value: |
        - [ ] todo 1
        - [ ] todo 2
        - [ ] todo 3
        - [ ] todo 4
    validations:
      required: true
