name: 'Planning Algorithm Week'
description: 'Algorithm week-based task planning'
title: '[Week1] EunseoPark'
labels: ['week', 'problems']
body:
  - type: markdown
    attributes:
      value: |
        ## 예제
  - type: checkboxes
    id: example-problems
    attributes:
      label: 예제 문제
      options:
        - label: 문제 1
        - label: 문제 2

  - type: markdown
    attributes:
      value: |
        ## 과제
  - type: checkboxes
    id: assignment-problems
    attributes:
      label: 과제 문제
      options:
        - label: 문제 1
        - label: 문제 2
